### PR TITLE
Remove code duplication normalizing timestamp in a dedicated method

### PR DESCRIPTION
**Pull request by tommyblue**
@aricooperdavis following our talking I made an attempt to make the code clearer when normalizing.
Moreover I moved the code in a separate method so there's no more code duplication.

### CODE REVIEW

**Comment by aricooperdavis** [comment]
Nice improvement, thank you!

**Comment by ronison** [comment]
I tested the script with Honor Band 4 file and was almost are ok. Only the timestamp '.000Z' string add that i need adjust to 'Z'. 
Great work. 
Best regards.

**Comment by aricooperdavis** [comment]
Thanks @ronison - could you just confirm that the Honor Band 4 requires [line 456](https://github.com/aricooperdavis/Huawei-TCX-Converter/blob/master/Huawei-TCX-Converter.py#L456) to read :

`line[0] = dt.utcfromtimestamp(line[0]).isoformat()+'.Z' #time`

rather than

`line[0] = dt.utcfromtimestamp(line[0]).isoformat()+'.000Z' #time`?

If so I will implement a command line argument/flag for the Honor Band 4. Also, if you could send over an example HiTrack file for me to have a look at that would be excellent!

Cheers

**Comment by ronison** [comment]
Hi @aricooperdavis,  In fact you need to change lines 347 and 456 as follows:

```
347: stats['start_time'] = dt.utcfromtimestamp(stats['start_time']).isoformat()+'Z'
...
456: line[0] = dt.utcfromtimestamp(line[0]).isoformat()+'Z' #time
```
I think this change would work for all devices and you would not need to add a parameter to it.

[HiTrack.txt](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3214809/HiTrack.txt)

**Comment by ronison** [comment]
This file was generated with the exercise started directly from the band, without the application. The first line was a problem.
[HiTrack_1557178410000155718218700030001.txt](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3215128/HiTrack_1557178410000155718218700030001.txt)

**Pull request merged**
